apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "five-g-appl.fullname" . }}
  labels:
    {{- include "five-g-appl.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "five-g-appl.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "five-g-appl.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "five-g-appl.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{ if .Values.initConfig.enabled }}
        - name: {{ .Chart.Name }}-get-ips
          image: accelleran/acc-generic-img:0.2.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: init-volume
              mountPath: /env-vars/
          command:
            - sh
            - "-c"
            - |
              /bin/bash <<'EOF'

              #!/bin/bash

              namespace="{{ .Release.Namespace }}"

              echo "" > /env-vars/env.env

              {{ range .Values.initConfig.ips }}

              ip=$(nslookup '{{ tpl .url $ }}'.${namespace}.svc.cluster.local | grep Address | tail -1 | awk '{ print $2 }')
              echo "'{{ .name }}'=$ip" >> /env-vars/env.env

              {{ end }}

              EOF
        {{ end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sh
            - "-c"
            - |
              /bin/bash <<'EOF'
              #!/bin/bash

              {{ if .Values.initConfig.enabled }}
              export $(xargs < /env-vars/env.env)
              {{ end }}

              {{ if .Values.testing }}
              echo {{ .Values.testing.value }} > /env-vars/test.txt
              {{ end }}

              {{ .Values.cmd }} {{- if .Values.args }}{{ range .Values.args }} {{ .name }} {{ .value }}{{ end }}{{- end }}

              EOF
          env: 
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ZLOG_CONF_PATH
              value: /5G/zlog.conf
            - name: BOOTSTRAP_INSTANCE_ID 
              value: {{ tpl .Values.bootstrapId . }}
            - name: BOOTSTRAP_FILENAME
              value: {{ .Values.bootstrapFile }}
            {{- if .Values.extraEnvs }}
            {{ toYaml .Values.extraEnvs | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
          volumeMounts:
            - name: {{ include "five-g-appl.fullname" . }}-zlog-conf
              mountPath: /home/accelleran/5G/zlog.conf
              subPath: "zlog.conf"
            - name: {{ include "five-g-appl.fullname" . }}-ncstart
              mountPath: /home/accelleran/5G/ncstart
              subPath: "ncstart"
            - name: {{ include "five-g-appl.fullname" . }}-bootstrap
              mountPath: {{ .Values.bootstrapFile }}
              subPath: "bootstrap.txt"
            - name: init-volume
              mountPath: /env-vars/
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: init-volume
          emptyDir: {}
        - name: {{ include "five-g-appl.fullname" . }}-zlog-conf
          configMap:
            name: {{ include "five-g-appl.fullname" . }}-zlog-conf
        - name: {{ include "five-g-appl.fullname" . }}-ncstart
          configMap:
            name: {{ include "five-g-appl.fullname" . }}-ncstart
            defaultMode: 0777
        - name: {{ include "five-g-appl.fullname" . }}-bootstrap
          configMap:
            name: {{ include "five-g-appl.fullname" . }}-bootstrap


