FROM ubuntu:bionic-20181112
MAINTAINER Accelleran

RUN   apt-get update \
  &&  apt-get install -y iputils-ping vim

ENV 	DEBIAN_FRONTEND noninteractive

RUN 	echo 'deb [trusted=yes] http://jenkins.ant.accelleran.com/packages/local-bionic /' > /etc/apt/sources.list

RUN 	apt-get update \
	&&	apt-get install -y python3 python3-yaml python3-pip

COPY	install-packages.py accelleran-packages.yml /tmp/
RUN 	/tmp/install-packages.py ap

RUN 	pip3 install pyang==2.2.1

RUN 	wget -q "http://jenkins.ant.accelleran.com/extra-files/go.tgz"; \
		echo "ea4caddf76b86ed5d101a61bc9a273be5b24d81f0567270bb4d5beaaded9b567 *go.tgz" | sha256sum -c -; \
		tar -C /usr/local -xzf go.tgz; \
		rm go.tgz; \
		export PATH="/usr/local/go/bin:$PATH"; \
		go version

CMD 	["/bin/bash"]

RUN		groupadd --gid 1000 accelleran \
	&&	useradd -m \
			--home-dir /home/accelleran_ \
			--shell /bin/bash \
			--gid accelleran \
			--uid 1000 \
			accelleran \
	&&  echo 'accelleran ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# Make scons use python3
RUN 	sed -i "s%#! /usr/bin/python2%#! /usr/bin/python3%" /usr/bin/scons

USER accelleran
ENV HOME /home/accelleran
ENV PATH $PATH:/opt/klocwork/bin/:/usr/local/go/bin
WORKDIR /5G

COPY ./native/amfControllerAppl.exe .
COPY ./native/cuUpAppl.exe .
COPY ./native/cuUpControllerAppl.exe .
COPY ./native/dsCtrlAppl.exe .
COPY ./native/duControllerAppl.exe .
COPY ./native/e1CpAppl.exe .
COPY ./native/e1sctpUpAppl.exe .
COPY ./native/f1apIntfAppl.exe .
COPY ./native/gnbControllerAppl.exe .
COPY ./native/lib/ ./lib/
COPY ./native/monAppl.exe .
COPY ./native/ngapAppl.exe .
COPY ./native/pmControllerAppl.exe .
COPY ./native/redis-cli .
COPY ./native/redis-server .
COPY ./native/resMgrAppl.exe .
COPY ./native/resMgrUpAppl.exe .
COPY ./native/rrCtrlAppl.exe .
COPY ./native/sctpCpAppl.exe .
COPY ./native/testerAppl.exe .
COPY zlog_printf.conf .
COPY zlog_syslog.conf .
COPY run-test .

CMD "/bin/bash"
