{{- if .Values.initGetConfig }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "five-g-appl.fullname" . }}-cluster-role-binding
  namespace: {{ .Release.Namespace }}
subjects:  
- kind: ServiceAccount
  name: {{ include "five-g-appl.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:  
  kind: ClusterRole
  name: {{ include "five-g-appl.fullname" . }}-cluster-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
