apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "acc-common.fullname" . }}-rpc-cucp
  labels:
    {{- include "acc-common.labels.5g" . | nindent 4 }}
data:
  cucp-rpc.py: |
    from netconf_client.connect import connect_ssh
    from netconf_client.ncclient import Manager

    HOST = "{{ tpl .Values.initNetconfDefaultPath.host . }}"
    PORT = 830

    session = connect_ssh(host=HOST, port=PORT, username="helm", password="helm")
    mgr = Manager(session, timeout=120)

    defPathCuCp = """<config>
    <netconf-config xmlns="http://accelleran.com/ns/yang/accelleran-netconf-config" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0" xc:operation="replace">
        <default-path>/accelleran-gnb-cu-cp:gnb-cu-cp</default-path>
    </netconf-config> </config>"""

    print(mgr.edit_config(config=defPathCuCp,target='running', default_operation=None))

