apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "acc-common.fullname" . }}-rpcs
  labels:
    {{- include "acc-common.labels.5g" . | nindent 4 }}
data:
  reload-models.xml: |
    <reload-models xmlns="http://accelleran.com/ns/yang/accelleran-netconf-config" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0"/>
  set-default-path-to-cucp.xml: |
    <netconf-config xmlns="http://accelleran.com/ns/yang/accelleran-netconf-config" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0" xc:operation="replace">
        <default-path>/accelleran-gnb-cu-cp:gnb-cu-cp</default-path>
    </netconf-config>
  set-default-path-to-cuup.xml: |
    <netconf-config xmlns="http://accelleran.com/ns/yang/accelleran-netconf-config" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0" xc:operation="replace">
        <default-path>/accelleran-gnb-cu-up:gnb-cu-up</default-path>
    </netconf-config>
  shutdown.xml: |
    <shutdown xmlns="http://accelleran.com/ns/yang/accelleran-netconf-config" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0"/>

  {{- if and (.Values.initEditConfig.enabled) (gt (len .Values.initEditConfig.config) 0) }}

  {{- range $index, $configRpc := .Values.initEditConfig.config }}
  init-edit-config-{{- $index -}}.xml: |
    {{- tpl $configRpc $ | nindent 4 }}
  {{- end }}

  {{- end }}
