{{ if .Values.configOnBoot.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "five-g-appl.fullname" . }}-config-cw
  labels:
    {{- include "five-g-appl.labels" . | nindent 4 }}
data:
  config-rpc.txt: {{ toYaml (tpl .Values.configOnBoot.config .) | nindent 4 }}
  cw-netconf-config.py: |
    from pathlib import Path
    from netconf_client.connect import connect_ssh
    from netconf_client.ncclient import Manager
    import time

    HOST = "{{ tpl .Values.configOnBoot.host . }}"
    PORT = 830

    session = connect_ssh(host=HOST, port=PORT, username="helm", password="helm")
    mgr = Manager(session, timeout=120)
    
    config_rpc = Path("/home/accelleran/5G/rpcs/config-rpc.txt").read_text()

    rc_config = f"<config>{config_rpc}</config>"
    
    print("Sending NetConf configuration RPC: {rc_config}".format(rc_config=rc_config))
    
    try:
      print(mgr.edit_config(config=rc_config,target='running', default_operation=None))
      print("***** Successfully set NetConf Configuration for Cell Wrapper!")
    except Exception as e:
      print("***** Failed to set NetConf Configuration for Cell Wrapper!")
      print(e)
    
    rc_unlock_admin_state = """
                <config xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
                  <cell-wrapper xmlns="http://accelleran.com/ns/yang/accelleran-granny" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0" xc:operation="replace">
                    <admin-state>unlocked</admin-state>
                  </cell-wrapper>
                </config>
                """
    
    try:
      print(mgr.edit_config(config=rc_unlock_admin_state,target='running', default_operation=None))
      print("***** Successfully unlocked Cell Wrapper Admin State!")
    except Exception as e:
      print("***** Failed to unlock Cell Wrapper Admin State!")
      print(e)
{{ end }} 
