apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "five-g-appl.fullname" . }}-rpc-cw
  labels:
    {{- include "five-g-appl.labels" . | nindent 4 }}
data:
  cw-rpc.py: |
    from netconf_client.connect import connect_ssh
    from netconf_client.ncclient import Manager

    HOST = "{{ tpl .Values.initNetconfDefaultPath.host . }}"
    PORT = 830

    session = connect_ssh(host=HOST, port=PORT, username="helm", password="helm")
    mgr = Manager(session, timeout=120)

    defPath = """<config>
    <netconf-config xmlns="http://accelleran.com/ns/yang/accelleran-netconf-config" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0" xc:operation="replace">
      <default-path>/accelleran-granny:granny</default-path>
    </netconf-config> </config>"""

    try:
      print(mgr.edit_config(config=defPath, target='running', default_operation=None))
      print("***** Successfully set default path for Cell Wrapper!")
    except Exception as e:
      print("***** Failed to set default path for Cell Wrapper!")
      print(e)


