apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "acc-common.fullname" . }}-rpc-model
  labels:
    {{- include "acc-common.labels.5g" . | nindent 4 }}
data:
  model-rpc.py: |
    from pathlib import Path
    from netconf_client.connect import connect_ssh
    from netconf_client.ncclient import Manager

    HOST = "localhost"
    PORT = 830

    session = connect_ssh(host=HOST, port=PORT, username="helm", password="helm")
    mgr = Manager(session, timeout=120)

    models_template = Path("/home/accelleran/5G/models.txt").read_text()
    models = f"<config>{models_template}</config>"

    print(mgr.edit_config(config=models,target='running', default_operation=None))

    reload = """<reload-models xmlns="http://accelleran.com/ns/yang/accelleran-netconf-config" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0"/>"""
    print(mgr.dispatch(reload))
