apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "five-g-appl.fullname" . }}
  labels:
    {{- include "five-g-appl.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "five-g-appl.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "five-g-appl.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "five-g-appl.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: {{ .Chart.Name }}-check-redis
          image: "{{ .Values.initImage.repository }}:{{ tpl .Values.initImage.tag . }}"
          imagePullPolicy: {{ .Values.initImage.pullPolicy }}
          command:
            - sh
            - "-c"
            - |
              /bin/bash <<'EOF'

              #!/bin/bash

              until [ "$(redis-cli -h {{ tpl .Values.redisConfig.hostname . }} -p {{ tpl .Values.redisConfig.port . }} ping)" == "PONG" ]; do sleep 1; done;
              echo "$(date) Redis ready"

              EOF
        - name: {{ .Chart.Name }}-get-configs
          image: "{{ .Values.initImage.repository }}:{{ tpl .Values.initImage.tag . }}"
          imagePullPolicy: {{ .Values.initImage.pullPolicy }}
          volumeMounts:
            - name: init-volume
              mountPath: /init-configs/
          command:
            - sh
            - "-c"
            - |
              /bin/bash <<'EOF'

              #!/bin/bash

              {{ if .Values.initGetConfig }}

              {{ range .Values.initGetConfig }}

              value=$(kubectl get {{ .resourceType }} {{ tpl .resourceName $ }} -n {{ tpl .resourceNamespace $ }} -o json | jq "{{ .field }}")

              echo "{{ .envName }}=$value" >> /init-configs/env.env

              {{ end }}

              {{ end }}

              EOF
        {{ if or .Values.initNetconfModel.enabled .Values.initNetconfDefaultPath.enabled }}
        - name: {{ .Chart.Name }}-config-netconf-model
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ tpl .Values.image.tag . | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ZLOG_CONF_PATH
              value: /5G/zlog.conf
            - name: BOOTSTRAP_INSTANCE_ID
              value: {{ tpl .Values.bootstrapId . }}
            - name: BOOTSTRAP_FILENAME
              value: {{ .Values.bootstrapFile }}
            - name: NATS_SERVICE_URL
              value: "nats://{{ tpl .Values.nats.url . }}:{{ tpl .Values.nats.port . }}"
            {{- if .Values.extraEnvs }}
            {{ toYaml .Values.extraEnvs | nindent 12 }}
            {{- end }}
          ports:
            - name: {{ .Values.netconfService.name }}
              containerPort: {{ .Values.netconfService.port }}
              protocol: {{ .Values.netconfService.protocol }}
          volumeMounts:
            - name: {{ include "five-g-appl.fullname" . }}-rpc-model
              mountPath: /home/accelleran/5G/rpcs/model-rpc.py
              subPath: "model-rpc.py"
            - name: {{ include "five-g-appl.fullname" . }}-zlog-conf
              mountPath: /home/accelleran/5G/zlog.conf
              subPath: "zlog.conf"
            - name: {{ include "five-g-appl.fullname" . }}-ncstart
              mountPath: /home/accelleran/5G/ncstart
              subPath: "ncstart"
            - name: {{ include "five-g-appl.fullname" . }}-bootstrap
              mountPath: {{ .Values.bootstrapFile }}
              subPath: "bootstrap.txt"
            - name: {{ include "five-g-appl.fullname" . }}-check-netconf
              mountPath: /home/accelleran/5G/rpcs/check-netconf.py
              subPath: "check-netconf.py"
            - name: {{ include "five-g-appl.fullname" . }}-rpc-cucp
              mountPath: /home/accelleran/5G/rpcs/cucp-rpc.py
              subPath: "cucp-rpc.py"
            - name: {{ include "five-g-appl.fullname" . }}-rpc-cuup
              mountPath: /home/accelleran/5G/rpcs/cuup-rpc.py
              subPath: "cuup-rpc.py"
            - name: {{ include "five-g-appl.fullname" . }}-rpc-cw
              mountPath: /home/accelleran/5G/rpcs/cw-rpc.py
              subPath: "cw-rpc.py"
            - name: {{ include "five-g-appl.fullname" . }}-config-cw
              mountPath: /home/accelleran/5G/rpcs/cw-netconf-config.py
              subPath: "cw-netconf-config.py"
            - name: {{ include "five-g-appl.fullname" . }}-delete-rpc
              mountPath: /home/accelleran/5G/rpcs/netconf-delete-config.py
              subPath: "netconf-delete-config.py"
          command:
            - sh
            - "-c"
            - |
              /bin/bash <<'EOF'

              #!/bin/bash

              ls

              # Start netconf in the background
              {{ .Values.cmd }} {{- if .Values.args }}{{ range .Values.args }} {{ .name }} {{ .value }}{{ end }}{{- end }} &

              # Add needed APT repositories
              echo "deb http://archive.ubuntu.com/ubuntu/ focal main restricted
              deb http://archive.ubuntu.com/ubuntu/ focal-updates main restricted
              deb http://archive.ubuntu.com/ubuntu/ focal universe
              deb http://archive.ubuntu.com/ubuntu/ focal-updates universe
              deb http://archive.ubuntu.com/ubuntu/ focal multiverse
              deb http://archive.ubuntu.com/ubuntu/ focal-updates multiverse
              deb http://archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse
              deb http://security.ubuntu.com/ubuntu/ focal-security main restricted
              deb http://security.ubuntu.com/ubuntu/ focal-security universe
              deb http://security.ubuntu.com/ubuntu/ focal-security multiverse" > /etc/apt/sources.list

              # ensure pip is available
              apt update && DEBIAN_FRONTEND=noninteractive apt -y install python3-pip

              # upgrade pip
              python3 -m pip install -U pip

              # Install netconf python lib
              pip3 install netconf-client==1.7.1

              # make sure that netconf is running
              python3 rpcs/check-netconf.py
              
              {{ if .Values.configOnBoot.deleteExistingConfig }}
              # If the delete config job is enabled, run the following script
              python3 /home/accelleran/5G/rpcs/netconf-delete-config.py
              {{ end }}

              {{ if .Values.initNetconfModel.enabled }}
              # Run model-rpc.py script
              python3 rpcs/model-rpc.py
              {{ end }}

              {{ if .Values.initNetconfDefaultPath.enabled }}

              {{ if eq ( tpl .Values.initNetconfDefaultPath.componentType . ) "cucp" }}

              python3 /home/accelleran/5G/rpcs/cucp-rpc.py >> rpcs/rpc-log.txt

              {{ else if eq ( tpl .Values.initNetconfDefaultPath.componentType . ) "cuup" }}

              python3 /home/accelleran/5G/rpcs/cuup-rpc.py >> rpcs/rpc-log.txt
              
              {{ else if eq ( tpl .Values.initNetconfDefaultPath.componentType . ) "cw" }}

              cat /home/accelleran/5G/rpcs/cw-rpc.py
              python3 /home/accelleran/5G/rpcs/cw-rpc.py

              {{ end }}

              {{ end }}
              
              
              {{- if .Values.configOnBoot.enabled }}
              {{ if eq ( tpl .Values.configOnBoot.configId . ) "cw" }}
              # Run cw-netconf-config.py script
              python3 /home/accelleran/5G/rpcs/cw-netconf-config.py
              {{ end }}
              {{- end }}
              
              exit 0

              EOF
        {{ end }}

      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ tpl .Values.image.tag . | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sh
            - "-c"
            - |
              /bin/bash <<'EOF'
              #!/bin/bash

              {{ if .Values.initGetConfig }}

              export $(xargs < /init-configs/env.env)

              {{ if .Values.testing }}
              echo {{ .Values.testing.value }} > /init-configs/test.txt
              {{ end }}

              {{ end }}

              {{ .Values.cmd }} {{- if .Values.args }}{{ range .Values.args }} {{ .name }} {{ tpl .value $ }}{{ end }}{{- end }}

              EOF
          env: 
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ZLOG_CONF_PATH
              value: /5G/zlog.conf
            - name: BOOTSTRAP_INSTANCE_ID 
              value: {{ tpl .Values.bootstrapId . }}
            - name: BOOTSTRAP_FILENAME
              value: {{ .Values.bootstrapFile }}
            - name: NATS_SERVICE_URL
              value: "nats://{{ tpl .Values.nats.url . }}:{{ tpl .Values.nats.port . }}"
            {{- if .Values.extraEnvs }}
            {{ toYaml .Values.extraEnvs | nindent 12 }}
            {{- end }}
          ports:
            - name: {{ .Values.netconfService.name }}
              containerPort: {{ .Values.netconfService.port }}
              protocol: {{ .Values.netconfService.protocol }}
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
          lifecycle:
            preStop:
              exec:
                command: [ '/bin/sh', '-c', 'pkill -15 -e {{ .Values.cmd | trimPrefix "./" | trimSuffix ".exe" | trunc 15  }}' ]
          volumeMounts:
            - name: {{ include "five-g-appl.fullname" . }}-zlog-conf
              mountPath: /home/accelleran/5G/zlog.conf
              subPath: "zlog.conf"
            - name: {{ include "five-g-appl.fullname" . }}-ncstart
              mountPath: /home/accelleran/5G/ncstart
              subPath: "ncstart"
            - name: {{ include "five-g-appl.fullname" . }}-bootstrap
              mountPath: {{ .Values.bootstrapFile }}
              subPath: "bootstrap.txt"
            - name: init-volume
              mountPath: /init-configs/
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if or (.Values.nodeSelector) (eq (tpl .Values.draxNodeSelectorEnabled .) "true") }}
      nodeSelector:
        {{ if .Values.nodeSelector }}
          {{- toYaml .Values.nodeSelector | nindent 8 }}
        {{ end }}
        {{ if eq (tpl .Values.draxNodeSelectorEnabled .) "true" }}
          {{- tpl (toYaml .Values.draxNodeSelector) $ | nindent 8 }}
        {{ end }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: init-volume
          emptyDir: {}
        - name: {{ include "five-g-appl.fullname" . }}-zlog-conf
          configMap:
            name: {{ include "five-g-appl.fullname" . }}-zlog-conf

        - name: {{ include "five-g-appl.fullname" . }}-ncstart
          configMap:
            name: {{ include "five-g-appl.fullname" . }}-ncstart
            defaultMode: 0777
        - name: {{ include "five-g-appl.fullname" . }}-bootstrap
          configMap:
            name: {{ include "five-g-appl.fullname" . }}-bootstrap

        - name: {{ include "five-g-appl.fullname" . }}-rpc-model
          configMap:
            name: {{ include "five-g-appl.fullname" . }}-rpc-model

        - name: {{ include "five-g-appl.fullname" . }}-rpc-cucp
          configMap:
            name: {{ include "five-g-appl.fullname" . }}-rpc-cucp

        - name: {{ include "five-g-appl.fullname" . }}-rpc-cuup
          configMap:
            name: {{ include "five-g-appl.fullname" . }}-rpc-cuup

        - name: {{ include "five-g-appl.fullname" . }}-check-netconf
          configMap:
            name: {{ include "five-g-appl.fullname" . }}-check-netconf

        - name: {{ include "five-g-appl.fullname" . }}-rpc-cw
          configMap:
            name: {{ include "five-g-appl.fullname" . }}-rpc-cw

        - name: {{ include "five-g-appl.fullname" . }}-config-cw
          configMap:
            name: {{ include "five-g-appl.fullname" . }}-config-cw

        - name: {{ include "five-g-appl.fullname" . }}-delete-rpc
          configMap:
            name: {{ include "five-g-appl.fullname" . }}-delete-rpc




