apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "five-g-appl.fullname" . }}
  labels:
    {{- include "five-g-appl.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "five-g-appl.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "five-g-appl.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "five-g-appl.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: {{ .Chart.Name }}-check-redis
          image: "{{ .Values.initImage.repository }}:{{ tpl .Values.initImage.tag . }}"
          imagePullPolicy: {{ .Values.initImage.pullPolicy }}
          command:
            - sh
            - "-c"
            - |
              /bin/bash <<'EOF'

              #!/bin/bash

              until [ "$(redis-cli -h {{ tpl .Values.redisConfig.hostname . }} -p {{ tpl .Values.redisConfig.port . }} ping)" == "PONG" ]; do sleep 1; done;
              echo "$(date) Redis ready"

              EOF
        - name: {{ .Chart.Name }}-get-configs
          image: "{{ .Values.initImage.repository }}:{{ tpl .Values.initImage.tag . }}"
          imagePullPolicy: {{ .Values.initImage.pullPolicy }}
          volumeMounts:
            - name: init-volume
              mountPath: /init-configs/
          command:
            - sh
            - "-c"
            - |
              /bin/bash <<'EOF'

              #!/bin/bash

              {{ if .Values.initGetConfig }}

              {{ range .Values.initGetConfig }}

              value=$(kubectl get {{ .resourceType }} {{ tpl .resourceName $ }} -n {{ tpl .resourceNamespace $ }} -o json | jq "{{ .field }}")

              echo "{{ .envName }}=$value" >> /init-configs/env.env

              {{ end }}

              {{ end }}

              EOF
        {{ if or .Values.initNetconfModel.enabled .Values.initNetconfDefaultPath.enabled }}
        - name: {{ .Chart.Name }}-config-netconf-model
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ tpl .Values.image.tag . | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ZLOG_CONF_PATH
              value: /5G/zlog.conf
            - name: BOOTSTRAP_INSTANCE_ID
              value: {{ tpl .Values.bootstrapId . }}
            - name: BOOTSTRAP_FILENAME
              value: {{ .Values.bootstrapFile }}
            - name: NATS_SERVICE_URL
              value: "nats://{{ tpl .Values.nats.url . }}:{{ tpl .Values.nats.port . }}"
            {{- if .Values.extraEnvs }}
            {{ toYaml .Values.extraEnvs | nindent 12 }}
            {{- end }}
          ports:
            - name: {{ .Values.netconfService.name }}
              containerPort: {{ .Values.netconfService.port }}
              protocol: {{ .Values.netconfService.protocol }}
          volumeMounts:
            - name: {{ include "five-g-appl.fullname" . }}-ncstart
              mountPath: /home/accelleran/5G/ncstart
              subPath: "ncstart"

            - name: {{ include "five-g-appl.fullname" . }}-zlog-conf
              mountPath: /home/accelleran/5G/zlog.conf
              subPath: "zlog.conf"
            - name: {{ include "five-g-appl.fullname" . }}-bootstrap
              mountPath: {{ .Values.bootstrapFile }}
              subPath: "bootstrap.txt"

            - name: {{ include "five-g-appl.fullname" . }}-models
              subPath: "reload"
              mountPath: /home/accelleran/5G/rpcs/models-reload.xml

            - name: {{ include "five-g-appl.fullname" . }}-netconf-config
              subPath: "delete"
              mountPath: /home/accelleran/5G/rpcs/netconf-config-delete.xml

            - name: {{ include "five-g-appl.fullname" . }}-cucp
              subPath: "default-path"
              mountPath: /home/accelleran/5G/rpcs/cucp-default-path.xml

            - name: {{ include "five-g-appl.fullname" . }}-cuup
              subPath: "default-path"
              mountPath: /home/accelleran/5G/rpcs/cuup-default-path.xml

            - name: {{ include "five-g-appl.fullname" . }}-cw
              subPath: "default-path"
              mountPath: /home/accelleran/5G/rpcs/cw-default-path.xml
            {{- if .Values.configOnBoot.enabled }}
            - name: {{ include "five-g-appl.fullname" . }}-cw
              subPath: "config"
              mountPath: /home/accelleran/5G/rpcs/cw-config.xml
            - name: {{ include "five-g-appl.fullname" . }}-cw
              subPath: "unlock-admin-state"
              mountPath: /home/accelleran/5G/rpcs/cw-unlock-admin-state.xml
            - name: {{ include "five-g-appl.fullname" . }}-cw
              subPath: "lock-admin-state"
              mountPath: /home/accelleran/5G/rpcs/cw-lock-admin-state.xml
            - name: {{ include "five-g-appl.fullname" . }}-cw
              subPath: "get"
              mountPath: /home/accelleran/5G/rpcs/cw-get.xml
            {{- end }}

          command:
            - sh
            - "-c"
            - |
              /bin/bash <<'EOF'

              #!/bin/bash

              ls

              # Start netconf in the background
              {{ .Values.cmd }} {{- if .Values.args }}{{ range .Values.args }} {{ .name }} {{ .value }}{{ end }}{{- end }} &

              ./ncclient \
                {{- if .Values.configOnBoot.deleteExistingConfig }}
                --edit /home/accelleran/5G/rpcs/netconf-config-delete.xml \
                {{- end }}
                {{- if .Values.initNetconfModel.enabled }}
                --edit models.txt \
                --custom rpcs/models-reload.xml \
                {{- end }}
                {{- if .Values.initNetconfDefaultPath.enabled }}
                  {{- if eq ( tpl .Values.initNetconfDefaultPath.componentType . ) "cucp" }}
                --edit rpcs/cucp-default-path.xml \
                  {{- else if eq ( tpl .Values.initNetconfDefaultPath.componentType . ) "cuup" }}
                --edit rpcs/cuup-default-path.xml \
                  {{- else if eq ( tpl .Values.initNetconfDefaultPath.componentType . ) "cw" }}
                --edit rpcs/cw-default-path.xml \
                  {{- end }}
                {{- end }}
                {{- if .Values.configOnBoot.enabled }}
                --edit rpcs/cw-config.xml \
                --edit rpcs/cw-unlock-admin-state.xml \
                --get-config rpcs/cw-get.xml \
                {{- end }}
                --port 830

              exit 0
              EOF
        {{ end }}

      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ tpl .Values.image.tag . | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sh
            - "-c"
            - |
              /bin/bash <<'EOF'
              #!/bin/bash

              {{ if .Values.initGetConfig }}

              export $(xargs < /init-configs/env.env)

              {{ if .Values.testing }}
              echo {{ .Values.testing.value }} > /init-configs/test.txt
              {{ end }}

              {{ end }}

              {{ .Values.cmd }} {{- if .Values.args }}{{ range .Values.args }} {{ .name }} {{ tpl .value $ }}{{ end }}{{- end }}

              EOF
          env: 
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ZLOG_CONF_PATH
              value: /5G/zlog.conf
            - name: BOOTSTRAP_INSTANCE_ID 
              value: {{ tpl .Values.bootstrapId . }}
            - name: BOOTSTRAP_FILENAME
              value: {{ .Values.bootstrapFile }}
            - name: NATS_SERVICE_URL
              value: "nats://{{ tpl .Values.nats.url . }}:{{ tpl .Values.nats.port . }}"
            {{- if .Values.extraEnvs }}
            {{ toYaml .Values.extraEnvs | nindent 12 }}
            {{- end }}
          ports:
            - name: {{ .Values.netconfService.name }}
              containerPort: {{ .Values.netconfService.port }}
              protocol: {{ .Values.netconfService.protocol }}
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
          lifecycle:
            preStop:
              exec:
                command: [ '/bin/sh', '-c', 'pkill -15 -e {{ .Values.cmd | trimPrefix "./" | trimSuffix ".exe" | trunc 15  }}' ]
          volumeMounts:
            - name: {{ include "five-g-appl.fullname" . }}-ncstart
              mountPath: /home/accelleran/5G/ncstart
              subPath: "ncstart"
            - name: {{ include "five-g-appl.fullname" . }}-zlog-conf
              mountPath: /home/accelleran/5G/zlog.conf
              subPath: "zlog.conf"
            - name: {{ include "five-g-appl.fullname" . }}-bootstrap
              mountPath: {{ .Values.bootstrapFile }}
              subPath: "bootstrap.txt"
            - name: init-volume
              mountPath: /init-configs/
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if or (.Values.nodeSelector) (eq (tpl .Values.draxNodeSelectorEnabled .) "true") }}
      nodeSelector:
        {{ if .Values.nodeSelector }}
          {{- toYaml .Values.nodeSelector | nindent 8 }}
        {{ end }}
        {{ if eq (tpl .Values.draxNodeSelectorEnabled .) "true" }}
          {{- tpl (toYaml .Values.draxNodeSelector) $ | nindent 8 }}
        {{ end }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: init-volume
          emptyDir: {}

        - name: {{ include "five-g-appl.fullname" . }}-ncstart
          configMap:
            name: {{ include "five-g-appl.fullname" . }}-ncstart
            defaultMode: 0777

        - name: {{ include "five-g-appl.fullname" . }}-zlog-conf
          configMap:
            name: {{ include "five-g-appl.fullname" . }}-zlog-conf
        - name: {{ include "five-g-appl.fullname" . }}-bootstrap
          configMap:
            name: {{ include "five-g-appl.fullname" . }}-bootstrap

        - name: {{ include "five-g-appl.fullname" . }}-models
          configMap:
            name: {{ include "five-g-appl.fullname" . }}-models
        
        - name: {{ include "five-g-appl.fullname" . }}-netconf-config
          configMap:
            name: {{ include "five-g-appl.fullname" . }}-netconf-config

        - name: {{ include "five-g-appl.fullname" . }}-cucp
          configMap:
            name: {{ include "five-g-appl.fullname" . }}-cucp

        - name: {{ include "five-g-appl.fullname" . }}-cuup
          configMap:
            name: {{ include "five-g-appl.fullname" . }}-cuup

        - name: {{ include "five-g-appl.fullname" . }}-cw
          configMap:
            name: {{ include "five-g-appl.fullname" . }}-cw
