nats:
  enabled: true

  nameOverride: "nats-5g"

  customLabels:
    drax/technology: 5g

  service:
    serviceName: '{{ include "nats.fullname" . }}'
    client:
      name: "natsport"
      port: 4222
#      nodePort:
    cluster:
      name: "clusterport"
      port: 6222
#      nodePort:
    monitoring:
      name: "consoleport"
      port: 8222
#      nodePort:

  draxNodeSelectorEnabled: "false"
  draxNodeSelector:
    draxName: "main"

redis:
  enabled: true

  nameOverride: "redis-5g"

  draxNodeSelectorEnabled: "false"
  draxNodeSelector:
    draxName: "main"

  # The version of the Docker image to use
  version: "redis20190206"

  # Custom labels for the deployment
  customLabels:
    drax/technology: 5g

  # The External IP of where NATS is installed
  natsIp: 10.55.1.2

  # The port NATS is using, check in the above settings of NATS
  natsPort: 31100

  # Backup the redis db when the pod is terminated
  backup:
    # Enabled or disable this feature
    enabled: true
    # Choose after how many days should the backed up DBs be deleted
    deleteAfterDay: 7

  service:
    type: NodePort
    port: 6379
#    nodePort:
    name: "redisport"
    serviceName: '{{ include "redis.fullname" . }}'

  persistence:
    accessModes:
      - ReadWriteMany
    enabled: true
    size: 10Gi
    storageClassName: acc-redis-5g
    type: pvc
    ### TESTING
    #hostPath: /opt/pods/acc-redis
    ### Production
    hostPath: /opt/pods/redis-storage-5g

metallb:
  # This installs the MetalLB LoadBalancer. Please make sure to do the required preparation before enabling the installation:
  # https://metallb.universe.tf/installation/
  # If you have your own Load Balancer in Kubernetes, you can skip this installation - set it to false.
  enabled: false

  configInline:
    address-pools:
      - name: default
        protocol: layer2
        addresses:
          - 10.55.1.20-10.55.1.60