apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "acc-common.fullname" . }}
  labels:
    {{- include "acc-common.labels.5g" . | nindent 4 }}
spec:
  serviceName: {{ include "acc-common.fullname" . }}-service
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ tpl .Values.numOfCuUps . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "acc-common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "acc-common.labels.5g" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "acc-common.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ tpl .Values.image.tag . | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{ if .Values.developerMode.enabled }}
          command:
            - sh
            - "-c"
            - |
              /bin/bash <<'EOF'
              echo "export __APPID=e1_cp_${HOSTNAME##*-}" > /home/accelleran/5G/dev/environment.sh
              chmod +x /home/accelleran/5G/dev/environment.sh
              while true; do sleep 30; done;
              EOF
          {{ else }}
          command:
            - sh
            - "-c"
            - |
              /bin/sh <<'EOF'
              echo e1_cp_${HOSTNAME##*-}
              __APPID=e1_cp_${HOSTNAME##*-} {{ .Values.cmd }} {{- if .Values.args }}{{ range .Values.args }} {{ .name }} {{ .value }}{{ end }}{{- end }}
              EOF
          {{ end }}
          env:
            - name: NATS_SERVICE_URL
              value: nats://{{ tpl .Values.nats.url . }}:{{ tpl .Values.nats.port . }}
            - name: ZLOG_CONF_PATH
              value: /home/accelleran/5G/zlog.conf
            - name: BOOTSTRAP_FILENAME
              value: {{ .Values.bootstrapFile }}
            - name: JAEGER_AGENT_HOST
              value: {{ tpl .Values.jaegerAgentHost . }}
            - name: __APPNAME
              value: e1cp
            {{- if .Values.extraEnvs }}
            {{ toYaml .Values.extraEnvs | nindent 12 }}
            {{- end }}
#          ports:
#            - name: http
#              containerPort: 80
#              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
          volumeMounts:
            - name: {{ include "acc-common.fullname" . }}-zlog-conf
              mountPath: /home/accelleran/5G/zlog.conf
              subPath: "zlog.conf"
            - name: {{ include "acc-common.fullname" . }}-bootstrap
              mountPath: {{ .Values.bootstrapFile }}
              subPath: "bootstrap.txt"
            {{ if and (.Values.developerMode.enabled) (.Values.developerMode.hostPath) }}
            - name: dev-work-dir
              mountPath: /home/accelleran/5G/dev/
            {{ end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          lifecycle:
            preStop:
              exec:
                command: [ '/bin/sh', '-c', 'pkill -15 -e {{ .Values.cmd | trimPrefix "./" | trimSuffix ".exe" | trunc 15  }}' ]
      {{- if or (.Values.nodeSelector) (eq (tpl .Values.draxNodeSelectorEnabled .) "true") }}
      nodeSelector:
        {{ if .Values.nodeSelector }}
          {{- toYaml .Values.nodeSelector | nindent 8 }}
        {{ end }}
        {{ if eq (tpl .Values.draxNodeSelectorEnabled .) "true" }}
          {{- tpl (toYaml .Values.draxNodeSelector) $ | nindent 8 }}
        {{ end }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ include "acc-common.fullname" . }}-zlog-conf
          configMap:
            name: {{ include "acc-common.fullname" . }}-zlog-conf

        - name: {{ include "acc-common.fullname" . }}-bootstrap
          configMap:
            name: {{ include "acc-common.fullname" . }}-bootstrap

        {{ if and (.Values.developerMode.enabled) (.Values.developerMode.hostPath) }}
        - name: dev-work-dir
          hostPath:
            path: {{ .Values.developerMode.hostPath }}
        {{ end }}
