{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "acc-common.fullname" . }}
  labels:
    {{- include "acc-common.labels.5g" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 38472
      targetPort:
      protocol: SCTP
      name: f1
  selector:
    {{- include "acc-common.selectorLabels" . | nindent 4 }}
{{- end -}}
