apiVersion: v1
kind: ConfigMap
metadata:
  name: conf-5g-config
data:
  5GConfig.toml: |-
    protobuf_file="messages_5g.pb"

    [options]
    {{ range .Values.options }}
    {{ .name }}="{{ .value }}"
    {{ end }}
