apiVersion: v2
name: acc-5g-cu-cp
description: Accelleran 5G CU CP Components

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 5.0.0-alpha

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "R3.2.0_grimbergen"
# THIS IS FOR DOCUMENTATION. REAL TAG CONTROL IN VALUES FILE!

# Dependencies
dependencies:
  - name: netconf
    condition: netconf.enabled
    version: 2.1.0
    repository: https://accelleran.github.io/5g-helm-charts/
  - name: amf-controller
    condition: amf-controller.enabled
    version: 0.7.0
    repository: https://accelleran.github.io/5g-helm-charts/
  - name: cu-up-controller
    condition: cu-up-controller.enabled
    version: 0.5.0
    repository: https://accelleran.github.io/5g-helm-charts/
  - name: ds-ctrl
    condition: ds-ctrl.enabled
    version: 1.0.0
    repository: https://accelleran.github.io/5g-helm-charts/
  - name: du-controller
    condition: du-controller.enabled
    version: 0.5.0
    repository: https://accelleran.github.io/5g-helm-charts/
  - name: e1-cp
    condition: e1-cp.enabled
    version: 1.0.0
    repository: https://accelleran.github.io/5g-helm-charts/
  - name: f1-ap
    condition: f1-ap.enabled
    version: 1.0.0
    repository: https://accelleran.github.io/5g-helm-charts/
  - name: gnb-controller
    condition: gnb-controller.enabled
    version: 0.5.0
    repository: https://accelleran.github.io/5g-helm-charts/
  - name: ng-ap
    condition: ng-ap.enabled
    version: 1.0.0
    repository: https://accelleran.github.io/5g-helm-charts/
  - name: pm-controller
    condition: pm-controller.enabled
    version: 0.5.0
    repository: https://accelleran.github.io/5g-helm-charts/
  - name: res-mgr
    condition: res-mgr.enabled
    version: 0.5.0
    repository: https://accelleran.github.io/5g-helm-charts/
  - name: rr-ctrl
    condition: rr-ctrl.enabled
    version: 1.0.0
    repository: https://accelleran.github.io/5g-helm-charts/
  - name: sctp-e1
    condition: sctp-e1.enabled
    version: 1.0.0
    repository: https://accelleran.github.io/5g-helm-charts/
  - name: sctp-f1
    condition: sctp-f1.enabled
    version: 1.0.0
    repository: https://accelleran.github.io/5g-helm-charts/
  - name: sctp-ng
    condition: sctp-ng.enabled
    version: 1.0.0
    repository: https://accelleran.github.io/5g-helm-charts/
  - name: ho-tester
    condition: ho-tester.enabled
    version: 0.2.0
    repository: https://accelleran.github.io/5g-helm-charts/

