{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "acc-common.fullname" . }}
  labels:
    {{- include "acc-common.labels.5g" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: UDP
      name: ho-tester
      {{ if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{ end }}
  selector:
    {{- include "acc-common.selectorLabels" . | nindent 4 }}
{{- end -}}
