apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "five-g-appl.fullname" . }}
  labels:
    {{- include "five-g-appl.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "five-g-appl.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "five-g-appl.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "five-g-appl.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: {{ .Chart.Name }}-get-init-configs
          image: "{{ .Values.initGetConfigImage.repository }}:{{ tpl .Values.initGetConfigImage.tag . }}"
          imagePullPolicy: {{ .Values.initGetConfigImage.pullPolicy }}
          volumeMounts:
            - name: init-volume
              mountPath: /init-configs/
          command:
            - sh
            - "-c"
            - |
              /bin/bash <<'EOF'

              #!/bin/bash

              {{ if .Values.initGetConfig }}

              {{ range .Values.initGetConfig }}

              value=$(kubectl get {{ .resourceType }} {{ tpl .resourceName $ }} -n {{ tpl .resourceNamespace $ }} -o json | jq "{{ .field }}")
              
              echo "{{ .envName }}=$value" >> /init-configs/env.env

              {{ end }}

              {{ end }}

              EOF
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ tpl .Values.image.tag . | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sh
            - "-c"
            - |
              /bin/bash <<'EOF'

              #!/bin/bash

              {{ if .Values.initGetConfig }}

              export $(xargs < /init-configs/env.env)

              echo {{ .Values.testing.value }} > /init-configs/test.txt

              {{ end }}

              {{ .Values.cmd }} {{- if .Values.args }}{{ range .Values.args }} {{ .name }} {{ tpl .value $ }}{{ end }}{{- end }}

              EOF
          env: 
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NATS_SERVICE_URL
              value: nats://{{ tpl .Values.nats.url . }}:{{ tpl .Values.nats.port . }}
            - name: ZLOG_CONF_PATH
              value: /5G/zlog.conf
            - name: BOOTSTRAP_FILENAME
              value: {{ .Values.bootstrapFile }}
            {{- if .Values.extraEnvs }}
            {{ toYaml .Values.extraEnvs | nindent 12 }}
            {{- end }}
          ports:
            - name: gtpu
              containerPort: {{ .Values.gtpService.gtpUPort }}
              protocol: {{ .Values.gtpService.protocol }}
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
          volumeMounts:
            - name: {{ include "five-g-appl.fullname" . }}-zlog-conf
              mountPath: /5G/zlog.conf
              subPath: "zlog.conf"
            - name: init-volume
              mountPath: /init-configs/
            - name: {{ include "five-g-appl.fullname" . }}-bootstrap
              mountPath: {{ .Values.bootstrapFile }}
              subPath: "bootstrap.txt"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          lifecycle:
            preStop:
              exec:
                command: [ '/bin/sh', '-c', 'pkill -15 -e {{ .Values.cmd | trimPrefix "./" | trunc 15  }}' ]
      {{- if or (.Values.nodeSelector) (eq (tpl .Values.draxNodeSelectorEnabled .) "true") }}
      nodeSelector:
        {{ if .Values.nodeSelector }}
          {{- toYaml .Values.nodeSelector | nindent 8 }}
        {{ end }}
        {{ if eq (tpl .Values.draxNodeSelectorEnabled .) "true" }}
          {{- tpl (toYaml .Values.draxNodeSelector) $ | nindent 8 }}
        {{ end }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: init-volume
          emptyDir: {}
        - name: {{ include "five-g-appl.fullname" . }}-zlog-conf
          configMap:
            name: {{ include "five-g-appl.fullname" . }}-zlog-conf

        - name: {{ include "five-g-appl.fullname" . }}-bootstrap
          configMap:
            name: {{ include "five-g-appl.fullname" . }}-bootstrap
