apiVersion: v2
name: acc-5g-cu-up
description: Accelleran 5G CU UP Components

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 5.4.0-alpha
# UPDATE .global.topChart.version IN VALUES FILE TO MATCH!

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "R4.2.0_karmeliet"
# THIS IS FOR DOCUMENTATION. REAL TAG CONTROL IN VALUES FILE!

# Dependencies
dependencies:
  - name: acc-common
    version: 0.1.0
    repository: https://accelleran.github.io/helm-charts/
  - name: netconf
    condition: netconf.enabled
    version: 2.4.0
    repository: https://accelleran.github.io/5g-helm-charts/
  - name: ups
    condition: ups.enabled
    version: 2.1.1
    repository: https://accelleran.github.io/5g-helm-charts/
  - name: e1-sctp-up
    condition: e1-sctp-up.enabled
    version: 0.6.1
    repository: https://accelleran.github.io/5g-helm-charts/
  - name: res-mgr-up
    condition: res-mgr-up.enabled
    version: 0.6.1
    repository: https://accelleran.github.io/5g-helm-charts/
  - name: pm-controller-up
    condition: pm-controller-up.enabled
    version: 0.4.1
    repository: https://accelleran.github.io/5g-helm-charts/
  - name: controller-up
    condition: controller-up.enabled
    version: 0.2.1
    repository: https://accelleran.github.io/5g-helm-charts/
