apiVersion: v2
name: acc-5g-cu-up
description: Accelleran 5G CU UP Components

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 2.0.0-rc4

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "release-2.2-chimay-fb09544"

# Dependencies
dependencies:
  - name: cu-up
    condition: cu-up.enabled
    version: 0.5.0
    repository: https://accelleran.github.io/5g-helm-charts/
  - name: e1-sctp-up
    condition: e1-sctp-up.enabled
    version: 0.5.0
    repository: https://accelleran.github.io/5g-helm-charts/
  - name: res-mgr-up
    condition: res-mgr-up.enabled
    version: 0.5.0
    repository: https://accelleran.github.io/5g-helm-charts/
  - name: netconf
    condition: netconf.enabled
    version: 0.6.1
    repository: https://accelleran.github.io/5g-helm-charts/
  - name: pm-controller-up
    condition: pm-controller-up.enabled
    version: 0.3.0
    repository: https://accelleran.github.io/5g-helm-charts/
