#! /bin/bash

BASE_DIR=/5G
ROOT=/5G

ZLOG_PATH=${ROOT}/zlog_printf.conf
NATS_URL=nats://127.0.0.1:4222
RUN_PATH=${ROOT}

if [ $#==2 ]
then
	NATS_URL=$1
fi

export NATS_SERVICE_URL=${NATS_URL}
export LD_LIBRARY_PATH=${RUN_PATH}/lib
export ZLOG_CONF_PATH=${ZLOG_PATH}

echo "Starting e1cp" && (__APPNAME=e1cp ${RUN_PATH}/e1CpAppl.exe > ${RUN_PATH}/e1Cp.log 2>&1 &)
echo "Starting f1ap" && (__APPNAME=f1pap ${RUN_PATH}/f1apIntfAppl.exe --f1ap_id du_1 >${RUN_PATH}/f1ap.log 2>&1 &)
echo "Starting sctp" && (__APPNAME=sctpCp ${RUN_PATH}/sctpCpAppl.exe  --own 127.0.0.1 --ng 127.0.0.5 >${RUN_PATH}/sctp.log 2>&1 &)
echo "Starting ngap" && (__APPNAME=ngap ${RUN_PATH}/ngapAppl.exe  >${RUN_PATH}/ngap.log 2>&1 &)
echo "Starting duController" && (__APPNAME=duController ${RUN_PATH}/duControllerAppl.exe  >${RUN_PATH}/duController.log 2>&1 &)
echo "Starting cuUpController" && (__APPNAME=cuUpController ${RUN_PATH}/cuUpControllerAppl.exe >${RUN_PATH}/cuUpController.log 2>&1 &)
echo "Starting amfController" && (__APPNAME=amfController ${RUN_PATH}/amfControllerAppl.exe >${RUN_PATH}/amfController.log 2>&1 &)
echo "Starting gnbController" && (__APPNAME=gnbController ${RUN_PATH}/gnbControllerAppl.exe >${RUN_PATH}/gnbController.log 2>&1 &)
echo "Starting rrCtrl" && (__APPNAME=rrCtrl ${RUN_PATH}/rrCtrlAppl.exe >${RUN_PATH}/rrCtrl.log 2>&1 &)
echo "Starting dsCtrl" && (__APPNAME=dsCtrl ${RUN_PATH}/dsCtrlAppl.exe --rel_msec 500 >${RUN_PATH}/dsCtrl.log 2>&1 &)
echo "Starting resMgr" && (__APPNAME=resMgr ${RUN_PATH}/resMgrAppl.exe >${RUN_PATH}/resMgrAppl.log 2>&1 &)
echo "Starting resMgrUp" && (__APPNAME=resMgrUp ${RUN_PATH}/resMgrUpAppl.exe >${RUN_PATH}/resMgrUpAppl.log 2>&1 &)
echo "Starting e1sctpUp" && (__APPNAME=e1sctpUp ${RUN_PATH}/e1sctpUpAppl.exe  --own 127.0.0.2 --cucp 127.0.0.1 --pub 127.0.0.2 >${RUN_PATH}/e1sctpUp.log 2>&1 &)
echo "Starting cuUp" && (__APPNAME=cuUp ${RUN_PATH}/cuUpAppl.exe  --own 127.0.0.2 --pub 127.0.0.2 >${RUN_PATH}/cuUp.log 2>&1 &)
echo "Starting pmController" && (__APPNAME=pmController ${RUN_PATH}/pmControllerAppl.exe >${RUN_PATH}/pmController.log 2>&1 &)

sleep 1 && echo "Starting testerAppl" && ${RUN_PATH}/./testerAppl.exe --own 127.0.0.5 --cucp 127.0.0.1 --numLoops 3

