{{- if .Values.f1Service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "five-g-appl.fullname" . }}-f1
  labels:
    {{- include "five-g-appl.labels" . | nindent 4 }}
spec:
  type: {{ .Values.f1Service.type }}
  ports:
    - port: {{ .Values.f1Service.f1Port}}
      protocol: {{ .Values.f1Service.protocol }}
      name: f1
      {{ if .Values.f1Service.f1NodePort }}
      nodePort: {{ .Values.f1NodePort }}
      {{ end }}
  {{ if .Values.f1Service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.f1Service.loadBalancerIP }}
  {{ end }}
  selector:
    {{- include "five-g-appl.selectorLabels" . | nindent 4 }}
{{- end -}}
