{{- if .Values.e1Service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "five-g-appl.fullname" . }}-e1
  labels:
    {{- include "five-g-appl.labels" . | nindent 4 }}
spec:
  type: {{ .Values.e1Service.type }}
  ports:
    - port: {{ .Values.e1Service.e1Port}}
      protocol: {{ .Values.e1Service.protocol }}
      name: e1
      {{ if .Values.e1Service.e1NodePort }}
      nodePort: {{ .Values.e1NodePort }}
      {{ end }}
  {{ if .Values.e1Service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.e1Service.loadBalancerIP }}
  {{ end }}
  selector:
    {{- include "five-g-appl.selectorLabels" . | nindent 4 }}
{{- end -}}
