nkafka-5g:
  enabled: false

acc-fiveg-amf-tester:
  enabled: true

  draxNodeSelectorEnabled: "{{ .Values.global.draxNodeSelectorEnabled }}"

  draxNodeSelector:
    draxName: "{{ .Values.global.draxName }}"

  image:
    tag: "{{ .Values.global.tag }}"

  # NATS Settings
  nats:
    # URL of NATS
    url: "{{ .Values.global.natsUrl }}"

    # Port of NAST
    port: "{{ .Values.global.natsPort }}"

  initConfig:
    ips:
      - url: '{{ include "five-g-appl.fullname" . }}-gtp'
        name: "GTP_IP"

  args:
    - name: "--own"
      value: "$POD_IP"
    - name: "--numLoops"
      value: "1"

  gtpService:
    enabled: true
    type: LoadBalancer
    protocol: UDP
    gtpUPort: 2152
    loadBalancerIP: "{{ .Values.global.amfTester1GtpIp }}"
    # gtpUNodePort:

  ngControlService:
    enabled: true
    type: LoadBalancer
    protocol: SCTP
    port: 38412
    loadBalancerIP: "{{ .Values.global.amfTester1NgControlIp }}"
    # nodePort:

acc-fiveg-du-tester:
  enabled: false

acc-fiveg-amf-controller:
  enabled: false

acc-fiveg-cu-up:
  enabled: false

acc-fiveg-cu-up-controller:
  enabled: false

acc-fiveg-ds-ctrl:
  enabled: false

acc-fiveg-du-controller:
  enabled: false

acc-fiveg-e1-cp:
  enabled: false

acc-fiveg-e1-sctp-up:
  enabled: false

acc-fiveg-f1-ap:
  enabled: false

acc-fiveg-gnb-controller:
  enabled: false

acc-fiveg-ng-ap:
  enabled: false

acc-fiveg-pm-controller:
  enabled: false

acc-fiveg-res-mgr:
  enabled: false

acc-fiveg-res-mgr-up:
  enabled: false

acc-fiveg-rr-ctrl:
  enabled: false

acc-fiveg-sctp:
  enabled: false