nkafka-5g:
  enabled: false

acc-fiveg-amf-tester:
  enabled: false

acc-fiveg-du-tester:
  enabled: false

acc-fiveg-amf-controller:
  enabled: false

acc-fiveg-cu-up:
  enabled: true

  draxNodeSelectorEnabled: "{{ .Values.global.draxNodeSelectorEnabled }}"

  draxNodeSelector:
    draxName: "{{ .Values.global.draxName }}"

  image:
    tag: "{{ .Values.global.tag }}"

  # NATS Settings
  nats:
    # URL of NATS
    url: "{{ .Values.global.natsUrl }}"

    # Port of NAST
    port: "{{ .Values.global.natsPort }}"

  args:
    - name: "--own"
      value: "$POD_IP"
    - name: "--pub"
      value: "{{ .Values.global.cuUp1GtpIp }}"

  gtpService:
    enabled: true
    type: LoadBalancer
    protocol: UDP
    gtpUPort: 2152
    loadBalancerIP: "{{ .Values.global.cuUp1GtpIp }}"

acc-fiveg-cu-up-controller:
  enabled: false

acc-fiveg-ds-ctrl:
  enabled: false

acc-fiveg-du-controller:
  enabled: false

acc-fiveg-e1-cp:
  enabled: false

acc-fiveg-e1-sctp-up:
  enabled: false

acc-fiveg-f1-ap:
  enabled: false

acc-fiveg-gnb-controller:
  enabled: false

acc-fiveg-ng-ap:
  enabled: false

acc-fiveg-pm-controller:
  enabled: false

acc-fiveg-res-mgr:
  enabled: false

acc-fiveg-res-mgr-up:
  enabled: true

  draxNodeSelectorEnabled: "{{ .Values.global.draxNodeSelectorEnabled }}"

  draxNodeSelector:
    draxName: "{{ .Values.global.draxName }}"

  image:
    tag: "{{ .Values.global.tag }}"

  # NATS Settings
  nats:
    # URL of NATS
    url: "{{ .Values.global.natsUrl }}"

    # Port of NAST
    port: "{{ .Values.global.natsPort }}"

  redisConfig:
    hostname: "{{ .Values.global.redisHostname }}"
    port: "{{ .Values.global.redisPort }}"

  bootstrapId: "cuup_1"

acc-fiveg-rr-ctrl:
  enabled: false

acc-fiveg-sctp:
  enabled: false