nkafka-5g:

  # Enable or disable installation of component
  #   Value type: boolean
  #
  enabled: true


  # Special dRAX NodeSelector
  #   Description:  Besides the default NodeSelector field for each component,
  #                 there is a special dRAX NodeSelector. This can be shared
  #                 among all 5G Helm Charts to install all components on the
  #                 same node. To enable this feature, first set
  #                 "draxNodeSelectorEnabled" to "true" (using quotes for
  #                 string type!). Next, draxNodeSelector field is a map,
  #                 where you can input different labels to look for in nodes.
  #                 A default label is the "draxName", which can be shared
  #                 among all 5G Helm Charts. To have it shared, values from
  #                 the global-values.yaml are used. Therefore, a string to
  #                 reference those values should be placed.
  #   Value type:   string
  #   Example:
  #
  # draxNodeSelectorEnabled: "{{ .Values.global.draxNodeSelectorEnabled }}"
  # draxNodeSelector:
  #   draxName: "{{ .Values.global.draxName }}"
  #
  draxNodeSelectorEnabled: "{{ .Values.global.draxNodeSelectorEnabled }}"
  draxNodeSelector:
    draxName: "{{ .Values.global.draxName }}"


  # Version/tag of component
  #   Description:  The version/tag of the component's Docker image which is
  #                 used to pull it from DockerHub. The version/tag can be
  #                 specified per component, or this field can reference to
  #                 the global tag in the global-values.yaml.
  #   Value type:   string
  #   Example:
  #
  # image:
  #   tag: "{{ .Values.global.nkafka5gTag }}"
  #
  image:
    tag: "{{ .Values.global.nkafka5gTag }}"


  # Accelleran license configuration
  #   Description:  Accelleran software uses licenses. here you can configure those options.
  #                 enabled: can be set to true if the license is used, or false to use the
  #                 unlicensed version (FOR INTERNAL ACCELLERAN USE ONLY)
  #                 licenseSecretName: th elicense is stored as a Kubernetes secret. Here
  #                 you can specify the secret name where the license is located.
  #   Value type: string
  #   Example:
  #
  # accelleranLicense:
  #   enabled: false
  #   licenseSecretName: accelleran-license
  #
  accelleranLicense:
    enabled: false
    licenseSecretName: accelleran-license


  # Kafka URL
  #   Description:  The full URL, including the PORT at the end, to Kafka.
  #                 Used by NKafka to connect and publish data to Kafka.
  #   Value type:   string
  #   Example:
  #
  # kafkaUrl: "ric-acc-kafka.{{ .Release.Namespace }}:9092"
  #
  kafkaUrl: "ric-acc-kafka.{{ .Release.Namespace }}:9092"


  # NATS URL
  #   Description:  The full URL, including the PORT at the end, to NATS.
  #                 Used by NKafka to connect and subscribe to NATS.
  #   Value type:   string
  #   Example:
  #
  # nats://nats-service.default:4222
  #
  natsUrl: "nats-service.{{ .Release.Namespace }}:4222"


  # NKafka-5G Specific Options
  #   Description:  Specific NKafka-5G Application options
  #                 TBD
  #   Value type: map (dictionary), with 3 fields:
  #               name - the name of the option
  #               value - the value of the option (use quotes here for a literal copy to toml, an example,
  #                        if its a large number Helm can translate it to a format the application does not recognize,
  #                        like for the max_len option. Without the quotes it would be copied to .toml as 1.048756e06)
  #
  options:
    - name: "topic"
      value: "5gmessages"
    - name: "rewrite_timestamp"
      value: "never"
    - name: "max_len"
      value: "1048756"
    - name: "timeout"
      value: "1000"
    - name: "mask"
      value: "false"
    - name: "seq_mapper"
      value: "one"
    - name: "threads"
      value: "1"
    - name: "invert_service"
      value: "false"
    - name: "replicate_messages"
      value: "false"
    - name: "compact"
      value: "true"
    - name: "offset"
      value: "auto"
    - name: "subject"
      value: "topic"

acc-fiveg-amf-tester:
  enabled: false

acc-fiveg-du-tester:
  enabled: false

acc-fiveg-amf-controller:
  enabled: false

acc-fiveg-cu-up:
  enabled: false

acc-fiveg-cu-up-controller:
  enabled: false

acc-fiveg-ds-ctrl:
  enabled: false

acc-fiveg-du-controller:
  enabled: false

acc-fiveg-e1-cp:
  enabled: false

acc-fiveg-e1-sctp-up:
  enabled: false

acc-fiveg-f1-ap:
  enabled: false

acc-fiveg-gnb-controller:
  enabled: false

acc-fiveg-ng-ap:
  enabled: false

acc-fiveg-pm-controller:
  enabled: false

acc-fiveg-res-mgr:
  enabled: false

acc-fiveg-res-mgr-up:
  enabled: false

acc-fiveg-rr-ctrl:
  enabled: false

acc-fiveg-sctp:
  enabled: false

