##############################################################
# Global configuration options shared between all helm charts
##############################################################

global:

  ## Kubernetes Advertise Address
  ##   Description: Used as External address for services
  ##   Value type: string
  ##
  kubeIp: "10.55.1.2"


  ## NATS URL and PORT
  ##   Description: Used to configure the application to talk
  ##                to NATS
  ##   Value type: string
  ##
  natsUrl: "10.55.1.2"
  natsPort: "31000"


  ## Version of the 5G applications
  ##   Description: This is the version of the 5G application
  ##                in DockerHub.
  ##   Value type: string
  ##
  tag: "165d9f5"


  ## CU-UP GTP IP address
  ##   Description: This IP address is given out to the CU-UP.
  ##                It is created as a LoadBalancer service,
  ##                hence the IP needs to be in the IP pool
  ##                that the LoadBalancer is configured for.
  ##   Value type: string
  ##
  cuUp1GtpIp: "10.55.1.30"
  cuUp2GtpIp: "10.55.1.31"


  ## SCTP E1 and F1 interface IPs
  ##   Description: These IPs are given to the SCTP application
  ##                to use for the E1 and F1 interfaces. The
  ##                service type is LoadBalancer, hence the IPs
  ##                need to be in the IP pool that the
  ##                LoadBalancer is configured for.
  ##   Value type: string
  ##   Example:
  ##
  sctpE1Ip: "10.55.1.20"
  sctpF1Ip: "10.55.1.21"


  ## AMF Tester settings
  ##   Description: The AMF-Tester application has two services,
  ##                the GTP and NG-Control. Both need to have an
  ##                IP assigned to them. Both services are of
  ##                type LoadBalancer, hence the IPs need to be
  ##                in the IP pool that the LoadBalancer is
  ##                configured for.
  ##   Value type: string
  ##   Example:
  ##
  amfTester1GtpIp: "10.55.1.40"
  amfTester1NgControlIp: "10.55.1.41"
  amfTester2GtpIp: "10.55.1.43"
  amfTester2NgControlIp: "10.55.1.44"


  ## DU Tester settings
  ##   Description: The DU-Tester applications has the GTP service.
  ##                The service is of LoadBalancer type, hence the
  ##                IPs need to be in the IP pool that the
  ##                LoadBalancer is configured for.
  ##   Value type: string
  ##   Example:
  ##
  duTesterGtpIp: "10.55.1.50"


  ## Redis settings
  ##   Description: Certain application need to be able to reach
  ##                Redis. Here we configure the Redis hostname
  ##                and port.
  ##   Value type: string
  ##   Example:
  ##
  redisHostname: "10.55.1.2"
  redisPort: "32200"


  ## dRAX Specific Node Selector
  ##   Description: This is a shared value that can be used by
  ##                each individual helm chart in the nodeSelector
  ##                field. You can label your nodes in Kubernetes,
  ##                and use those labels to force each individual
  ##                application or all of them to be scheduled on a
  ##                particular node based on the label.
  ##                NOTE: You have to manually set it for each
  ##                helm chart.
  ##   Value type: string
  ##   Example:
  ##
  draxNodeSelectorName: "main"
