{{- if .Values.serviceAccount.create -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "acc-common.fullname" . }}-cluster-role-binding
  namespace: {{ .Release.Namespace }}
subjects:  
- kind: ServiceAccount
  name: {{ include "acc-common.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:  
  kind: Role
  name: {{ include "acc-common.fullname" . }}-cluster-role
  apiGroup: rbac.authorization.k8s.io

{{- end }}
