apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "five-g-appl.fullname" . }}-zlog-conf
  labels:
    {{- include "five-g-appl.labels" . | nindent 4 }}
data:
  zlog.conf: |
    [global]
    strict init = true
    buffer min = 64K
    buffer max = 64K
    rotate lock file = /tmp/zlog.lock
    
    [formats]
    printf_format = "%d(%b %d %H:%M:%S).%ms %8.8H %m%n"
    [rules]
    user.* >stdout ;printf_format    
