{{- if .Values.service.enabled -}}

{{ $count := (.Values.numberOfUpStacks | int) }}
{{- range untilStep 0 $count 1 }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "five-g-appl.fullname" $ }}-{{ . | toString }}
  labels:
    {{- include "five-g-appl.labels" $ | nindent 4 }}
    up-stack-id: {{ . | quote }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "five-g-appl.selectorLabels" $ | nindent 4 }}
    up-stack-id: {{ . | quote }}
---
{{- end }}

{{- end -}}
