{{- if .Values.gtpService.enabled -}}

{{ $count := (tpl .Values.numberOfUpStacks . | int) }}
{{- range untilStep 0 $count 1 }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "acc-common.fullname" $ }}-gtp-{{ . | toString }}
  labels:
    {{- include "acc-common.labels.5g" $ | nindent 4 }}
    up-stack-id: {{ . | quote }}
spec:
  type: {{ $.Values.gtpService.type }}
  {{ if $.Values.gtpService.externalTrafficPolicy }}
  externalTrafficPolicy: {{ tpl $.Values.gtpService.externalTrafficPolicy $ }}
  {{ end }}
  ports:
    - port: {{ $.Values.gtpService.gtpUPort }}
      protocol: {{ $.Values.gtpService.protocol }}
      name: gtpu
      {{ if contains "NodePort" $.Values.gtpService.type }}
      nodePort: {{ $.Values.gtpService.gtpUNodePort }}
      {{ end }}
  {{ if $.Values.gtpService.loadBalancerIP }}
  loadBalancerIP: {{ tpl $.Values.gtpService.loadBalancerIP $ }}
  {{ end }}
  selector:
    {{- include "acc-common.selectorLabels" $ | nindent 4 }}
    up-stack-id: {{ . | quote }}
---
{{- end }}

{{- end -}}
